/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        background: '#f7f9ff',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#eef1f7',
        'inverse-primary': '#91ccff',
        'inverse-surface': '#2d3135',
        'on-background': '#181c20',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'on-primary-container': '#fcfcff',
        'on-primary-fixed': '#001e31',
        'on-primary-fixed-variant': '#004b72',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#646464',
        'on-secondary-fixed': '#1b1c1c',
        'on-secondary-fixed-variant': '#474747',
        'on-surface': '#181c20',
        'on-surface-variant': '#3f4850',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fffbff',
        'on-tertiary-fixed': '#2d1600',
        'on-tertiary-fixed-variant': '#6a3b00',
        outline: '#707881',
        'outline-variant': '#bfc7d1',
        primary: '#006193',
        'primary-container': '#007bb8',
        'primary-fixed': '#cce5ff',
        'primary-fixed-dim': '#91ccff',
        secondary: '#5e5e5e',
        'secondary-container': '#e4e2e2',
        'secondary-fixed': '#e4e2e2',
        'secondary-fixed-dim': '#c8c6c6',
        surface: '#f7f9ff',
        'surface-bright': '#f7f9ff',
        'surface-container': '#ebeef4',
        'surface-container-high': '#e5e8ee',
        'surface-container-highest': '#e0e3e8',
        'surface-container-low': '#f1f4f9',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#d7dae0',
        'surface-tint': '#006496',
        'surface-variant': '#e0e3e8',
        tertiary: '#884e00',
        'tertiary-container': '#ab6300',
        'tertiary-fixed': '#ffdcbf',
        'tertiary-fixed-dim': '#ffb873',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        'margin-desktop': '40px',
        'margin-mobile': '16px',
        'stack-lg': '48px',
        'stack-md': '24px',
        'stack-sm': '8px',
        unit: '8px',
        'container-max': '1200px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'headline-lg': ['Manrope', 'system-ui', 'sans-serif'],
        'headline-md': ['Manrope', 'system-ui', 'sans-serif'],
        'headline-xl': ['Manrope', 'system-ui', 'sans-serif'],
        'label-sm': ['Inter', 'system-ui', 'sans-serif'],
        manrope: ['Manrope', 'system-ui', 'sans-serif'],
        inter: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
